### ISSUE TITLE
لینک اشتباه نیازمندی های نرم افزار

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#1]
لینک "نیازمندی های نرم افزار" در صفحه "نصب" به مسیر اشتباه پیوند خورده.

صفحه نصب
http://localhost/install/

لینک اشتباه
http://localhost/install/requirements.php
404 not found خطاش

لینک صحیح
http://localhost/requirements.php

**Comment by rezaei121** [comment]
درست شد.
https://github.com/rezaei121/raspina/compare/1.8.6...master
