### ISSUE TITLE
چند مورد جزیی

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#11]
اینکه سایت آیکون
favicon
نداره

فکر کنم چند متغیر در فایلهای زیر تعریف شدن اما استفاده نشن
backend/controllers/SiteController.php, line 21
`private $_user;`

common/components/browser.php, line 13
`private $_os = '';`

backend/modules/about/controllers/DefaultController.php, line 9
`use yii\web\UploadedFile;`

و اینکه نام این کلاس استاندارد نیست:
common/components/date.php
`class date extends Component`
**PSR-1**

**Comment by rezaei121** [comment]
common/components/date.php
کلا باید حذف بشه
یه کلاس تاریخ و زمان هم جایگزینش نوشتم که خیلی داغونه اول باید اون ادیت شه

**Comment by rezaei121** [comment]
بیا رفیق:
https://github.com/rezaei121/raspina/commit/4c311e99ab226b9cd6aecfd176095371241f1caa
:)
