### ISSUE TITLE
requirements.php -> PHP Intl Date Formatter

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#2]
در صفحه "نیازمندی ها" ی پروژه:
اکستنشن php_intl من غیرفعال هست
اما بهم پیام میده که باید غیرفعال شه.

و وقتی هم که فعالش می کنم، تایید میشه اما باز هم همون خطا رو میده

پیامش با اکستنشن غیرفعال
PHP Intl Date Formatter	**Failed**	Date Formatter	**"php_intl" should be disabled at php.ini**

پیامش با اکستنشن فعال
PHP Intl Date Formatter	**Passed**	Date Formatter	"php_intl" should be disabled at php.ini

**Comment by rezaei121** [comment]
اون خطا نیست، یادداشت یا توضیحاته
Memo
