### ISSUE TITLE
ترتیب autoload

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#22]
در این خط از فایل بوت:

https://github.com/rezaei121/raspina/blob/c482e477be4b83de38c3ff80e8e1f4fcf25a2c22/tests/_bootstrap.php#L5

اول اتولود فریم ورک لود شده، بعد اتولود کامپوزر... 
درصورتیکه در مستندات خود "یی" گفته شده اول اتولود کامپوزباشه و بعد "یی"

https://www.yiiframework.com/doc/guide/2.0/en/concept-autoloading
https://www.yiiframework.com/doc/guide/2.0/en/structure-entry-scripts
_فکر کنم موتور پی اچ پی رو مجبور به جستجوی اضافی می کنی_

**Comment by neoacevedo** [comment]
Project dead.

**Comment by rezaei121** [comment]
> Project dead.

Yii dead.

**Comment by neoacevedo** [comment]
Yii1, not Yii2

**Comment by rezaei121** [comment]
i know.
i meant yii2.
This framework is old. no significant updates. the new version has not been released for a long time. I no longer want to work with yii2.

**Comment by rezaei121** [comment]
> Yii1, not Yii2

i know.
i meant yii2.
This framework is old. no significant updates. the new version has not been released for a long time. I no longer want to work with yii2.

**Comment by neoacevedo** [comment]
You should the to set this repo in read-only mode.
