### ISSUE TITLE
Memcache و APC 

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#3]
Memcache و APC من این دو اسکتنشن رو غیرفعال کردم
و وقتی که به صفحه "نیازمندی ها" نگاه می کنم، با اینکه قرمز شده اما هیچ پیامی یا توضیحی به من نداده مه روشنشون کنم یا لازمه پروژه هستن یا...

Memcache extension	Warning	MemCache	
APC extension	Warning	ApcCache

**Comment by rezaei121** [comment]
قرمز یا زرد؟
هر دو اجباری نیستن و غیر فعال بودنشون برای نصب مشکلی ایجاد نمیکنه

**Comment by Yousha** [comment]
قرمز

رنگش درسته، غیر فعالن. اما اینکه هیج توضیحی ندارن برام مسلست

**Comment by rezaei121** [comment]
مطمئنی؟
غیر اجباری ها نهایتا در صورت فعال نبودن زرد میشن من روی لوکال تست گرفتم

**Comment by Yousha** [comment]
زرد؟ :D

http://uupload.ir/files/c0s7_untitled.png

**Comment by rezaei121** [comment]
خب این زرده دیگه :D

**Comment by Yousha** [comment]
آها... خب توضیح نداشتنشون طبیعیه؟

**Comment by rezaei121** [comment]
اره، وسعش نا همین حد بیشتر نیست :دی. البته باهات موافقم، توی نسخه های بعدی به جای استفاده از صفحه نیازمندی های خود فریمورک یک صفحه اختصاصی رسپینا درست میکنم

**Comment by Yousha** [comment]
آها، پس هیچی... 
enhancement

با اجازه اینو میبندم
