### ISSUE TITLE
Index of / بعد از نصب

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#4]
در حالت عادی/پیش فرض:

بعد از نصب کامل پروژه، هیچ فایل ایندکسی در پوشه اصلی پروژه نیست که من/کاربر رو به خانه و صفحه اصلی وبلاگ ببره

خود سرورم رو غیر فعال کردم htaccess البته من
حالا برفرض اینکه از nginx استفاده کنم
یا iis حتی

و همین باعث میشه که کلیه لینک های داخل وبلاگ نصب شده کار نکنن و 404 بدن

**Comment by rezaei121** [comment]
htaccess باید فعال باشه
nginx رو توی نسخه ی بعدی راه میندازم

**Comment by Yousha** [comment]
پس شاید بد نباشه موقع نصب از فعال بودنش مطمعن بشی؟
مثلاً
```
if (in_array('mod_rewrite', apache_get_modules()))
...
```

**Comment by rezaei121** [comment]
قرار گرفت

**Comment by rezaei121** [comment]
https://github.com/rezaei121/raspina/commit/4ca720dc42a8352237bb075776233ab71b83dbd4

**Comment by Yousha** [comment]
من آپاچی و مد rewrite رو نصب و فعال کردم
اما بازم این مشکل حل نشده

کماکان ایندکل دایرکتوری و فایل ها رو میاره

**Tag: 1.8.6**

**Comment by rezaei121** [comment]
فایل های .htaccess رو توی پروژه داری؟
3 تا باید باشه

**Comment by Yousha** [comment]
رفتی واسه من لینوکس کار شدی،:laughing:    دیگه گور بابای ویندوز؟ ها؟ :
:rofl: 

مشکل از این خطه
`<IfModule mod_rewrite.c>`
باید بشه
`<IfModule mod_rewrite>`
یا
`<IfModule mod_rewrite.so>`
تا با ویندوز سازگار بشه

الان لینوکس ندارم، ببین از این دوتا پایینی کدومشون با لینوکست سازگاره

**Comment by rezaei121** [comment]
من اگر توی ویندوز هم قرار باشه کد بزنم برای اجرا کردن پروژه یه لینوکس مجازی میسازم :پی
چک میکنم، اعمال میکنم
