### ISSUE TITLE
دسترسی مستقیم به فایلهای پی اچ پی

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#5]
دسترسی مستقیم از طریق نوار آدرس به کلیه فایلهای پی اچ پی امکانپذیره
فکر کنم فراموش کردی

http://localhost/backend/controllers/CommentController.php
Fatal error: Class 'yii\web\Controller' not found in C:\WWW\root\backend\controllers\CommentController.php on line 17

http://localhost/common/config/bootstrap.php
Fatal error: Class 'Yii' not found in C:\WWW\root\common\config\bootstrap.php on line 2

**Comment by rezaei121** [comment]
تست میکنم و این مشکل وجود نداره
The php page isn’t working
php is currently unable to handle this request.
من ویندوز ندارم به نظرت به خاطر ویندوز یا ومپ نیست مثلا؟

**Comment by Yousha** [comment]
نه، ارتباطی به ویندوز نداره
منظور من دسترسی مستقیم و باز کردن فایلها هستش...
**چیز خاصی نیست**، اما باید برطرف بشه، چون در بعضی از فایلها شاید امکان دادن پارامتر بصورت مستقیم باشه

مثلا در یک فایل مشترک/سراسری این رو تعریف کن:
`define('LOCAL_ACCESS', TRUE);`

و در اول همه فایلها اینو بذار:
`if (!defined('LOCAL_ACCESS')) exit;`
