### ISSUE TITLE
 execute() on boolean - \install\index.php - line 91

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#7]
پروژه رو دانلود و نصاب رو اجرا کردم. بعد فرم رو که **خالی** ارسال کردم مکانیزم نصاب بهم ریخت:

`Fatal error: Call to a member function execute() on boolean in C:\WWW\root\install\index.php on line 91`

فکر کنم چون چک کننده فرم رو غیر فعال کردی - در خط 39
```
//            foreach ($data as $k => $v)
//            {
//				$v = trim($v); //
//                if(empty($v) && $k != 'db_password')
//                {
//                    echo '<div class="error">تمام فیلد ها اجباری هستند لطفا آنها را با دقت پر کنید. <a href="../install/">صفحه نصب رسپینا</a></div>';
//                    return false;
//                }
//
//                $data[$k] = trim($v);
//            }
```

**Tag: 1.8.6**

**Comment by rezaei121** [comment]
ربطی به اون کامنت ها نداره.
بررسی میکنم

**Comment by rezaei121** [comment]
نصب کلا داخل پروژه قرار میگیره نه اینکه مثل الان جدا از اون باشه. در این صورت این اتفاقات دیگه نمیوفته
