### ISSUE TITLE
return false; - /install/index.php

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#8]
دلیل این
return false;
ها چیه؟ جایی این فایل نصاب رو اینکلود کردی و خروجیش رو میگیری؟
اگر نه و هدفت متوقف کردن عملیات/پردازش هست که باید از 
exit(1); یا exit;
استفاده کنی

و  حتی بجای همین توقف ها میتونی از
set_exception_handler
استفاده کنی، بدون نیاز به کد اضافی، خودشم پردازش رو متوقف میکنه

**Tag: 1.8.6**

**Comment by rezaei121** [comment]
اشتب شده :دی
با دید شی گرایی و تصور اینکه داخل کلاسم آبشاری کد نوشتم :پی
