### ISSUE TITLE
phar & branch

### ISSUE THREAD

**Issue by Yousha** [rezaei121/raspina#9]
اینکه نیازی به ضمیمه کردن فایل
composer.phar
در پروژه نیست. اگر کامپوزر نصب نشده باشه ضمیمه کردن این ابزار بی مصرفه. اما اگر نصب شده باشه خود سیستم(چه لینوکس چه ویندوز) داره. پس بازم بی مصرفه... 
همچنین بخاطر ملاحظات امنیتی و _بروز رسانی های مکرر برنامه کامپوزر_ هم قرارش نمیدن. 

اما فکرکنم تو باید کامپوزر رو _بصورت سراسری_ نصب کنی

بعضیا حتی **فایل قفل** و **محتویات وندور** رو هم قرار نمی دن.
vendor, .lock
حجم پروژه پایین میاد، دردسر سیستم کنترل ورژن برای تایید و کمپرس کردن و کامیت کردن هم کم میشه

و آخر اینکه این برنچ مسترت مال دولوپ یا جاریه؟
اگر آره نمی خوای به 
Develop یا Current 
تغییرش بدی اشتب نکنیم؟

**Tag: 1.8.6**

**Comment by rezaei121** [comment]
برنچ مستر رو به
dev
تغییر دادم اما متاسفانه کامیت های قبلی رو دیگه نمیشه کاری کرد همشون مستر  خوردن

**Comment by Yousha** [comment]
خب تغییر نام میدادی بجاش ساخت شاخه جدید

هر گزارشی که فکر می کنی باید بسته بشه ببند

**Comment by rezaei121** [comment]
توی قسمت تنظیمات تغییرش دادم
الان ببین درسته؟

**Comment by rezaei121** [comment]
composer.phar
حذف شد.
برنچ ست شد.

اگر محتویات 
vendor
رو حذف کنیم کاربر مجبور میشه با کامپوزر عملیات نصب رو انجام بدیه
فکر خیلی خوبیه و زحمت من رو کم میکنه
اما
کاربر عادی توی نصب به مشکل میخوره

**Comment by Yousha** [comment]
اغلب کاربرا معمولاً مستندات نصب رو می خونن
در اکثر پروژه ها  هم این پوشه رو قرار نمیدن تا هم پروژه سبک بشه و هم وابستگی ها توسط کاربر **بروز نصب بشه**
مثلاً +2
مثلا +3.1.
و...

اما آره، عده ای تازه وارد هستن و نمی تونن باهاش کار کنن
پس بنظرم فایل قفلش رو نذار با بقیه کاربرای حرفه ای بتونن بدون دستکاری، وابستگی ها رو بروز کنن

**Comment by rezaei121** [comment]
vendor
و یکسری چیزهای دیگه از گیت حذف شد
gitignore
رو یه نگاه بنداز
برای کاربر های مبتدی هم لینک دانلود جدا میذارم داخل وبلاگم

**Comment by Yousha** [comment]
خوب شده. اینا هم مال ایکلیپسه
local.properties
.settings/
